#define SAMTOOLS_VERSION "1.16.1"
#define SAMTOOLS_CC "gcc"
#define SAMTOOLS_CPPFLAGS ""
#define SAMTOOLS_CFLAGS "-g -Wall -O2"
#define SAMTOOLS_LDFLAGS ""
#define SAMTOOLS_HTSDIR "htslib-1.16"
#define SAMTOOLS_LIBS ""
#define SAMTOOLS_CURSES_LIB "-lcurses"
